### ISSUE TITLE
Metadata Refresh Thread Error

### ISSUE THREAD

**Issue by clockwinder** [williamjacksn/python-rainwave-client#94]
Running client V0.9.0, via Python 3.8.10 on Debian

When starting a new stream, I get this error every time.  
```
Exception in thread Thread-821 (_do_sync_thread):
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/rainwaveclient/channel.py", line 77, in _do_sync_thread
    self._sched_current = d['sched_current']
KeyError: 'sched_current'
```
Am I implementing something with threading or fetching this data incorrectly?

**Comment by williamjacksn** [comment]
Upgrade to version 0.10.0, then add logging to your program like this:

```python
import logging
logging.basicConfig(level=logging.DEBUG)
```

You should start seeing log messages printed for every Rainwave API call, including the response data. We can troubleshoot with that information.

**Comment by coldshouldermedia** [comment]
Logging was causing Python to crash, it seems the Rainwave Client is dumping huge amounts of data into the log. >250,000 characters.

It appears there are 3 large entries:
the first two entries are ~20,000 characters and start with: 
```
DEBUG:rainwaveclient.client:{'user': {'admin': False, 'tuned_in': False, 'perks': False, 'request_position': None, 'request_expires_at': None, 'rate_anything': False, 'avatar': 'removed', 'new_privmsg': 0, 'listen_key': 'removed', 'id': removed, 'name': 'removed', 'display_name': 'Anonymous', 'sid': 4, 'lock': False, 'lock_in_effect': False, 'lock_sid': None, 'lock_counter': 0, 'voted_entry': 0, 'listener_id': 0, 'uses_oauth': True}, 'album_diff': [{'id': 1640, 'cool': True, 'cool_lowest': 1649691094, 'newest_song_time': 0, 'rating': 3.8, 'name': 'Red Max'}], 'request_line':
```

Then it goes on to list many albums from, #-A-Z. ~200,000 characters (I've just included the beginning)
```
DEBUG:rainwaveclient.client:{'all_albums': [{'id': 2575, 'name': '10,000,000', 'rating': 4.2, 'cool': False, 'cool_lowest': 1649439736, 'fave': False, 'rating_user': 0.0, 'rating_complete': False, 'newest_song_time': 1371802767}, {'id': 1919, 'name': '1-Minute', 'rating': 3.0, 'cool': False, 'cool_lowest': 1649428172, 'fave': False, 'rating_user': 0.0, 'rating_complete': False, 'newest_song_time': 1378198408}, {'id': 1973, 'name': '2007 GOTO 1986', 'rating': 3.7, 'cool': True, 'cool_lowest': 1649514616, 'fave': False, 'rating_user': 0.0, 'rating_complete': False, 'newest_song_time': 1385186826},
```
Skipping the middle, and the end looks like:
```
{'id': 3218, 'name': 'Zoids Densetsu', 'rating': 3.0, 'cool': True, 'cool_lowest': 1649506124, 'fave': False, 'rating_user': 0.0, 'rating_complete': False, 'newest_song_time': 1476028624}, {'id': 2132, 'name': 'Zombie Nation', 'rating': 3.5, 'cool': False, 'cool_lowest': 1649365226, 'fave': False, 'rating_user': 0.0, 'rating_complete': False, 'newest_song_time': 1330804266}, {'id': 3229, 'name': 'µWIN', 'rating': 3.5, 'cool': False, 'cool_lowest': 1649432137, 'fave': False, 'rating_user': 0.0, 'rating_complete': False, 'newest_song_time': 1479091669}], 'api_info': {'exectime': 0.050339460372924805, 'time': 1649453589}}
```

At this point if logging is enabled the program becomes unresponsive.  If logging is disabled it keeps playing just fine, but `._sync_thread.is_alive()` returns `False`.

The debug info preceding the log info I initially posted reads:
```
DEBUG:rainwaveclient.client:{'user': {'admin': False, 'tuned_in': False, 'perks': False, 'request_position': None, 'request_expires_at': None, 'rate_anything': False, 'avatar': 'removed', 'new_privmsg': 0, 'listen_key': 'removed', 'id': removed, 'name': 'removed', 'display_name': 'Anonymous', 'sid': 4, 'lock': False, 'lock_in_effect': False, 'lock_sid': None, 'lock_counter': 0, 'voted_entry': None, 'listener_id': 7520880, 'uses_oauth': True}, 'api_info': {'exectime': 0.0005199909210205078, 'time': 1649453879}}
Exception in thread Thread-4 (_do_sync_thread):
Traceback (most recent call last):
  File "removed\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "removed\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "removed\Local\Programs\Python\Python310\lib\site-packages\rainwaveclient\channel.py", line 77, in _do_sync_thread
    self._sched_current = d['sched_current']
KeyError: 'sched_current'
```

Is this the information you're seeking?

**Comment by coldshouldermedia** [comment]
After upgrading to 0.10.0, 

Without logging I get:
```
Missing sched_current data in API response
Missing sched_next data in API response
Missing sched_history data in API response
```
every time a new stream is started.

But `._sync_thread.is_alive()` now returns `true`.

Would you still like the full debug log?  Rainwave entries are ~170,000 characters after ~2 seconds of streaming.

**Comment by williamjacksn** [comment]
The keys are right there (`sched_current`, `sched_next`, `sched_history`), and this is the same API call that the background thread would use. So I still don't know why you are getting a `KeyError`.

The `RainwaveChannel` object automatically caches schedule information. Part of the schedule information is when the currently playing song will end. If you request `chan.schedule_current` and the `RainwaveChannel` object already has data and the end time is still in the future, you will get the cached data. If the end time is in the past, the library will automatically request new data from the API.
